services:
  # Backend Service (NestJS)
  backend:
    build:
      context: ./mining_pools_api
    container_name: mining_pools_backend
    ports:
      - "3000:3000"  # Expose port 3000 for backend API
    networks:
      - mining_pools_network
    environment:
      - NODE_ENV=production
      - MONGO_DB_URI=mongodb://mongo:27017/mining_pools
    depends_on:
      - mongo

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./mining_pools_frontend
    container_name: mining_pools_frontend
    ports:
      - "3001:3001"  # Expose port 3001 for frontend
    networks:
      - mining_pools_network
  # MongoDB Service (for backend data storage)
  mongo:
    image: mongo:latest
    container_name: mining_pools_mongo
    ports:
      - "27017:27017"  # Expose MongoDB default port
    networks:
      - mining_pools_network
    volumes:
      - ./data/db:/data/db  # Persistent storage for MongoDB data

networks:
  mining_pools_network:
    driver: bridge
